FROM golang:1.23-alpine

RUN apk add --no-cache git \
    && go install github.com/pressly/goose/v3/cmd/goose@latest

WORKDIR /internal/storage/migrations
COPY internal/storage/migrations/ .

ENTRYPOINT ["goose"]