FROM golang:1.23-alpine

# Install goose and dependencies
RUN apk add --no-cache git \
    && go install github.com/pressly/goose/v3/cmd/goose@latest

WORKDIR /app/migrations
COPY . .

# Create the migrations directory in container
RUN mkdir -p /app/migrations

ENTRYPOINT ["goose"]