-- +goose Up
ALTER TABLE orders ADD COLUMN leather_cost DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN process_cost DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN total_cost DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN commission DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN tax DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN net_revenue DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN profit DECIMAL(10,2) NOT NULL DEFAULT 0;

-- +goose Down
ALTER TABLE orders DROP COLUMN leather_cost;
ALTER TABLE orders DROP COLUMN process_cost;
ALTER TABLE orders DROP COLUMN total_cost;
ALTER TABLE orders DROP COLUMN commission;
ALTER TABLE orders DROP COLUMN tax;
ALTER TABLE orders DROP COLUMN net_revenue;
ALTER TABLE orders DROP COLUMN profit;